### ISSUE TITLE
2.7 release

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#1209]
If you have feedback on what's needed for a 2.7 release, please comment!

* [Issues for 2.7](https://github.com/reactjs/react-rails/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.7)
* [PRs for 2.7](https://github.com/reactjs/react-rails/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.7)

# TODO for 2.7
- [x] Update changelog for [diffs since 2.6.2](https://github.com/reactjs/react-rails/compare/v2.6.2...master)
- [x] Verify the latest Shakapacker works with React-Rails
- [x] Confirm support for latest React 18 via Shakapacker
- [x] Consider updating the versions of React packaged with react-rails
- [x] Update to React 17 latest, as this was done for [React 16](https://github.com/reactjs/react-rails/commit/9b4bf58ce5d4117a6a1c8228af399baad268ab93#diff-402e1c44db611170cc92ebbc38cf8fb7b023ac3288b82b2fdeced8de12d2e02c)
- [ ] Update [Sample App](https://github.com/shakacode/react-rails-example-app) to master with latest Shakapacker

**Comment by ahangarha** [comment]
I also think we should add test for React-Rails + Shakapacker. I don't know if we should keep the test for React-Rails + Webpacker or not.

**Comment by justin808** [comment]
Webpacker v5.4 and before should work.

If the migration to shakapacker should be straightforward, then we should require that for react-rails v3.

**Comment by justin808** [comment]
@ahangarha what's left for 2.7 release? can you check off items as completed?

**Comment by ahangarha** [comment]
This is the status:

- ✅ Update changelog for [diffs since 2.6.2](https://github.com/reactjs/react-rails/compare/v2.6.2...master)
- ✅ Verify the latest Shakapacker works with React-Rails
- ⏭️ Confirm support for latest React 18 via Shakapacker
- ⏭️ Consider updating the versions of React packaged with react-rails
- ⏭️ Update to React 17 latest, as this was done for [React 16](https://github.com/reactjs/react-rails/commit/9b4bf58ce5d4117a6a1c8228af399baad268ab93#diff-402e1c44db611170cc92ebbc38cf8fb7b023ac3288b82b2fdeced8de12d2e02c)
- ⚠️ Update [Sample App](https://github.com/shakacode/react-rails-example-app) to master with latest Shakapacker

Tomorrow I can work on checking react 18 with shakapacker and hopefully upgrade to React 17.0.2. Working on the sample app would take more time. Regarding the old versions of dependencies, I cannot give any estimation on how long it would talk time. For that I might need some support.

**Comment by justin808** [comment]
Shipped.
