### ISSUE TITLE
compare/contrast and migration steps

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#1289]
1. Create a detailed compare/contrast of react_on_rails vs react-rails.
2. Create clear migration steps both from
  1. sprockets
  2. webpacker/shakapacker

**Comment by ahangarha** [comment]
# Todo
- [ ] In #1304 there is a brief feature comparison table. Is that sufficient to satisfy the first requirement?
- [x] Migration from react-rails 3 using Shakapacker
- [ ] Migration from react-rails 3 using Sprockets

**Comment by justin808** [comment]
@ahangarha we should break up the README and have a /docs folder

And not "Why to migrate?" but "Why migrate".

Use Grammarly!

**Comment by paul-mesnilgrente** [comment]
You haven't mentioned that SSR isn't free in react-on-rails which seems to be a big point to not miss in a `Why migrate` section.

**Comment by justin808** [comment]
@paul-mesnilgrente agree!

**Comment by ahangarha** [comment]
> We should break up the README and have a /docs folder
It is done.

> You haven't mentioned what parts aren't free in react-on-rails, it seems to be a very important distinction to make a decision.

True. But all of the mentioned features are provided by react_on_rails and demonstrated in the [react-webpack-rails-tutorial](https://github.com/shakacode/react-webpack-rails-tutorial) project.
