### ISSUE TITLE
Revisit initialization 

### ISSUE THREAD

**Issue by rmosolgo** [reactjs/react-rails#252]
There are a lot of issues popping up regarding how `react-rails` sets up & handles app initialization. I want to work out these problems. 

## To do 
- [x] Ensure support for `.js.jsx.erb` (https://github.com/reactjs/react-rails/issues/231)
- [x] Fix `jsx_transform_options` when precompile doesn't initialize (https://github.com/reactjs/react-rails/issues/192)
- [x] Fix long boot times (https://github.com/reactjs/react-rails/issues/249)
- [x] Ensure support for Sprockets 3 (https://github.com/reactjs/react-rails/issues/240)
- [x] Fix file copy permission issues (https://github.com/reactjs/react-rails/issues/175)
- [x] Address `sprockets-rails` compatibility issue (https://github.com/reactjs/react-rails/pull/268#issuecomment-103152635)

**Comment by rmosolgo** [comment]
I have some ideas to kick things off:

- Instead of copying files into the app directory, add different gem directories to the asset pipeline based on `config.react.variant`. (For example, if `:development`, then add `/vendor/development/`, whose copy of `react.js` is the dev build. If `:production`, add `/vendor/production`, whose `react.js` file is the production build. That way, no file copying on boot.)
- Decouple the server renderer, as suggested here: https://github.com/reactjs/react-rails/issues/143#issuecomment-76065541
- Write some failing tests for the initializers, fiddle with em til they work!

**Comment by rmosolgo** [comment]
`.jsx_transform_options` is a wont-fix for me, the work around is to assign `JSX.transform_options` directly and I think that's fine
