### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by rmosolgo** [reactjs/react-rails#307]
`master` has a _lot_ of changes. It was stuck for a bit with a `sprockets-rails` incompatibility. It will be great to get a new version out in the wild.

## Todo:

- [x] update vendored React.js, update VERSIONS.md
- [x] Does anyone have other specific to-dos????
- [x] update version in the readme, publish version

__Not todo__ (A couple of things I'm eyeing for 1.2):

- Improve documentation for extension points (transformer, renderer)
- Add extension point for the view helper 
- Develop a path for updating the react.js version without updating react-rails

**Comment by borisrorsvort** [comment]
Would there be a possibility to remove the extra wrapper tag around each component?  For some small components its just a pity to have div > span if you just want a span.

**Comment by rmosolgo** [comment]
Maybe possible, in the meantime you can use `tag: :span` to at least have `span > span` !

**Comment by borisrorsvort** [comment]
More generally it can lead to some issues when you have a base Component css Class and use :first-child or stuff like that. Plus If you're using components in a loop that leads to massively more nodes in Dom tree and eventually perfomance issue.

**Comment by rmosolgo** [comment]
:tada:  https://github.com/reactjs/react-rails/releases/tag/v1.1.0

**Comment by borisrorsvort** [comment]
:+1:  Well done! regarding the base extra wrapper. Shall I create another issue?

**Comment by rmosolgo** [comment]
Yes please!
