### ISSUE TITLE
react-rails 2.0

### ISSUE THREAD

**Issue by rmosolgo** [reactjs/react-rails#448]
There are some issues building up, I think they will need some breaking changes. Here's what's on my list. Do you have anything else that's missing?
- [x] Support Rails 5.0 
  - [x] Fix `before_filter` usage in ControllerLifecycle #404
  - [x] Fix messed up server rendering flow 
- [x] Support Sprockets 3
  -  ~~Figure out cases where assets aren't transformed  (#415, #431)~~
  - [x] Support precompiled assets (https://github.com/reactjs/react-rails/issues/443, PR:
    https://github.com/reactjs/react-rails/pull/430)
- [x] Support Sprockets 4 ?
- [x] Support Turbolinks 5
  - Stop warning about Turbolinks 2.2.4 
  - Update for new Turbolinks API 
  - Split UJS into different files, make `react_ujs` a manifest?
- [x] Reduce Rails dependency 
  - [x] Altogether here: #558 
  - ~~Basically, just merge this: https://github.com/reactjs/react-rails/pull/427~~
  - ~~Don't depend on sprockets #493~~ 
-  [x] Improve the flexibility of React addons 
  - use `webpacker`
  - ~~Support custom ReactJS builds (backed with npm & webpack, built into the apps asset directory)~~
  - ~~Expose `renderToString` etc without `//= require react-server` (https://github.com/reactjs/react-rails/issues/442)~~
- [x] General cleanup 
  - [x] Use `.js` files for CONSOLE_POLYFILL and CONSOLE_REPLAY
  - [x] Can we merge `engine.rb` and `railtie.rb`? They're almost the same thing, right?
  - [x] Fix replay_console + server rendering #555 
-  [x] Support `require()` environments #678 
  - Expose UJS 
  - Document custom component-fetching function 
- [x] Improve documentation 
  - ~~[ ] Improve YARD docs~~
  - ~~[ ] Split readme into guides & improve content~~
  - [x] Update readme

**Comment by twe4ked** [comment]
Thanks for creating this issue @rmosolgo. Looks like #450 could be a dot-point under _Support Rails 5.0_.

**Comment by rmosolgo** [comment]
Thanks, I added a note!

**Comment by SylarRuby** [comment]
I've seen this list for version 2. Ok, support for rails 5 as I'm getting this: https://github.com/reactjs/react-rails/issues/467

**Comment by connorshea** [comment]
Do you mean Sprockets 3 or Sprockets 4? At the moment I'm testing Turbolinks 5 and Sprockets 4.0.0.beta2 and `react-rails` isn't playing well with one or both of them.

**Comment by rmosolgo** [comment]
Oh, I didn't know Sprockets 4 was so close to launching! Will it be part of Rails 5? 

I expect Turbolinks 5 to be supported in the latest (1.6.2). Please open an issue if you have any trouble!

**Comment by connorshea** [comment]
@rmosolgo Upgrading from 3.x and 4.x: https://github.com/rails/sprockets/blob/master/UPGRADING.md

I don't think it'll be apart of Rails 5, at least not as far as I know.

**Comment by connorshea** [comment]
@rmosolgo and thank you very very much for maintaining the gem for so long and so well! I was so happy to see react-rails had already been upgraded to support Rails 5, most other gems were throwing deprecations warnings right and left.

**Comment by connorshea** [comment]
@rmosolgo update: It looks like this was entirely a Turbolinks 5 problem. Since Turbolinks 5 has no guide for updating, I didn't realize the events had changed, so all our JavaScript stopped loading.

Using Turbolinks Classic and Sprockets 5.0.0 works fine with react-rails, apologies!

**Comment by connorshea** [comment]
@rmosolgo you can probably remove the `renderToString` TODO, [React v15.0 will deprecate it](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html), and presumably remove it in v16.0

**Comment by rmosolgo** [comment]
They're still on `ReactDOMServer` though, right? I think we still need them somehow, that's how we implement server-side rendering!

For my part, I need `renderToString` in the browser for integrating with some other libraries, so I'd like to have a nice way to get it from react-rails!

**Comment by connorshea** [comment]
Not sure, I guess you'd have to test 15.0-rc1 to see what happens.

**Comment by drush** [comment]
Is React 15.0 support implicit for this issue, or should it be added to the checklist?  Don't see a 15.0 ticket elsewhere.

**Comment by rmosolgo** [comment]
@drush React 15 was merged in #512 and just shipped in 1.7.0 :)
