### ISSUE TITLE
First-class webpacker support

### ISSUE THREAD

**Issue by rmosolgo** [reactjs/react-rails#677]
We should have a well-documented happy path for using webpacker + react-rails 

Todo: 

- [x] support loading components from a pack #678 
- [x] deliver UJS to packs #678 
- [x] Generator should output to `app/javascripts/components` #684 
- [x] documentation #685 
- [x] server rendering (static packs) #683 
- [x] Support webpacker-but-not-sprockets environment #686 
- [x] Rename `SprocketsRenderer`?  #686 
- [x] server rendering from dev-server #687 
- [x] Fix generated `/components` folder
- [x] add UJS lookup fallback for hybrid webpacker-sprockets
- [x] Update for webpacker path change https://github.com/rails/webpacker/pull/237
- [x] Deploy UJS to npm
- [x] Update the description on GitHub

**Comment by gauravtiwari** [comment]
This is looking pretty good @rmosolgo 🎉  🍰

**Comment by rmosolgo** [comment]
:D Thanks! It's been a breeze working with webpacker, so thanks for your work on that!
